package uz.pdp.appnews.entity.enums;

public enum Permissions {
    ADD_USER, EDIT_USER, DELETE_USER, VIEW_USERS,
    ADD_ROLE, EDIT_ROLE, DELETE_ROLE, VIEW_ROLES,
    ADD_POST, EDIT_POST, DELETE_POST,
    ADD_COMMENT, EDIT_COMMENT, DELETE_COMMENT, DELETE_MY_COMMENT,


}
